Use queue for fanout and notify on failure

diff --git a/scripts/pull-queue b/scripts/pull-queue
--- a/scripts/pull-queue
+++ b/scripts/pull-queue
@@ -8,7 +8,7 @@
 
 pkg=""
 set -uo pipefail
-trap 's=$?; /send-pushover "$pkg Build Error" "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+trap 's=$?; /send-pushover "$pkg Build Error" "$0: Error on line "$LINENO": $BASH_COMMAND"; /reset $pkg; exit $s' ERR
 IFS=$'\n\t'
 
 # Requried environment variables
@@ -17,7 +17,7 @@ region=${AWS_REGION}                    # The AWS region the SQS queue is contai
 
 repo_name=${REPO_NAME}                  # The name of the DB file within the repository
 arch=${REPO_ARCH}                       # The architecture to build for (eg. x86_64)
-fanout_controller=${FANOUT_CONTROLLER}  # Name of the fanout controller function to invoke
+fanout_queue=${FANOUT_QUEUE}            # URL of the queue to send a completion or failure notification to
 aur_key=${AUR_KEY}                      # Name of the SSM parameter containing the signing key
 
 
@@ -72,12 +72,10 @@ while [ /bin/true ]; do
             /build-aur "$pkg" "$key_id"
 
             echo "Notifying queue of completion"
-            aws lambda invoke \
-                --function-name $fanout_controller \
-                --invocation-type "Event" \
-                --log-type "None" \
-                --payload "{\"PackageName\": \"${pkg}\", \"BuildStatus\": \"Complete\"}" \
-                no_file
+            aws sqs send-message \
+                --region ${region} \
+                --queue-url ${fanout_queue} \
+                --message-body "{\"PackageName\": \"${pkg}\", \"BuildStatus\": \"Complete\"}"
         fi
         
         # Pull repo DB file
